### ISSUE TITLE
Items Won't install

### ISSUE THREAD

**Issue by craigs100** [vendrhub/vendr-checkout#39]
Umb 10.5.1, Vendr 3.1.12, Vendr.Checkout V3.0.0

Nuget package installed ok.  Rebuilt and restarted site. In the Vendr Checkout section nothing happens when Install is clicked. But the following appears in the browser console:-
```

angular.js:99 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.8.3/$injector/nomod?p0=vendr.resources
    at angular.js:99:1
    at angular.js:2331:17
    at b (angular.js:2252:38)
    at Object.module (angular.js:2329:14)
    at vendrcheckout.resource.js?d=638231520600000000:19:13
    at vendrcheckout.resource.js?d=638231520600000000:21:2
(anonymous) @ angular.js:99
(anonymous) @ angular.js:2331
b @ angular.js:2252
(anonymous) @ angular.js:2329
(anonymous) @ vendrcheckout.resource.js?d=638231520600000000:19
(anonymous) @ vendrcheckout.resource.js?d=638231520600000000:21

angular.js:99 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.8.3/$injector/nomod?p0=vendr
    at angular.js:99:1
    at angular.js:2331:17
    at b (angular.js:2252:38)
    at Object.module (angular.js:2329:14)
    at installer.controller.js?d=638231520600000000:27:13
    at installer.controller.js?d=638231520600000000:29:2
(anonymous) @ angular.js:99
(anonymous) @ angular.js:2331
b @ angular.js:2252
(anonymous) @ angular.js:2329
(anonymous) @ installer.controller.js?d=638231520600000000:27
(anonymous) @ installer.controller.js?d=638231520600000000:29

angular.js:99 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.8.3/$injector/nomod?p0=vendr
    at angular.js:99:1
    at angular.js:2331:17
    at b (angular.js:2252:38)
    at Object.module (angular.js:2329:14)
    at installer.controller.js?d=638231520600000000:56:13
    at installer.controller.js?d=638231520600000000:58:2
(anonymous) @ angular.js:99
(anonymous) @ angular.js:2331
b @ angular.js:2252
(anonymous) @ angular.js:2329
(anonymous) @ installer.controller.js?d=638231520600000000:56
(anonymous) @ installer.controller.js?d=638231520600000000:58

angular.js:15697 Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.3/$controller/ctrlreg?p0=Vendr.Checkout.Controllers.InstallerDashboardController
    at angular.js:99:1
    at angular.js:11787:17
    at ea (angular.js:10818:34)
    at p (angular.js:10603:32)
    at g (angular.js:9942:13)
    at angular.js:9807:30
    at Object.link (angular.js:29993:9)
    at angular.js:1391:15
    at Ca (angular.js:11376:9)
    at p (angular.js:10695:11) '<div ng-include="property.view" class="ng-scope">'
```
    
    Please advise.

**Comment by mattbrailsford** [comment]
I think this is potentially fixed in 3.1.0 where we ensure Vendr Checkout is run after Vendr because the errors you report are saying that Vendr modules aren't present so the Vendr Checkout scripts are loading too soon.

Unfortunately yea that update also bumped the minimum Umbraco dependency to v11. I'll take a look on monday to see if that can be back ported.

**Comment by craigs100** [comment]
Thanks. Prob too late for me for this one, but at least it'll be fixed for others. And the next one I might have to do on V10 ;)

**Comment by mattbrailsford** [comment]
Too late because you need it today? or because you've already gone down another route?

**Comment by mattbrailsford** [comment]
If you need it now, you should find a 3.0.1-beta0001 build on the unstable nuget feed here https://nuget.outfield.digital/unstable/vendr/v3/index.json in a few minutes which should fix it if you want to use that.

**Comment by craigs100** [comment]
That link is a bunch of json that I don't know what to do with I'm afraid. I've built the checkout in Umbraco now, just going through the templates.

**Comment by mattbrailsford** [comment]
That link is a custom nuget feed, you'd need to set it up in Visual Studio like so https://www.forevolve.com/en/articles/2017/08/06/how-to-use-a-custom-nuget-feed-in-visual-studio-2017/

But if you've gone the custom route no worries 👍

**Comment by craigs100** [comment]
Thanks for that. I installed it and it's exactly the same error coming up. I made sure I cleared out all the old App_Plugins/VendrCheckout code first before reinstalling. I've tried a couple of times but it still fails. I'm finding copying the custom route from the demo store particularly hard because there are so many little models here and there, half of which don't pertain to my site.  That's why I was keen to just install the package and have it done. It seemed so easy on Paul's video.  Not so the custom route. I'll just have to bash on.

**Comment by mattbrailsford** [comment]
Ok, well I'll have to take a close look Monday. Was just seeing if a quick fix could help you out. Hope you get the custom checkout figures out 👍

**Comment by craigs100** [comment]
I'm giving up with the custom route. It's just too difficult to reconcile all the nested missing references from the demo site. So if you could get the package to install on V10 I'd be very grateful.

**Comment by mattbrailsford** [comment]
I’ll setup a v10 site on Monday and test. 

Are the listed errors the only js errors you are seeing? The above would suggest the Vendr js files are either loading too late, or not loading at all. Could be a permissions issue or a caching issue or something.

**Comment by craigs100** [comment]
Yes, those are the only errors I see. They appear as soon as you click on the "Vendr Checkout" menu item.  The install page loads but nothing happens when you click the "Install" button.

Thanks.

**Comment by mattbrailsford** [comment]
Thought I'd quickly try and test this and unfortunately I can't seem to replicate it.

The steps I followed:

1. Installed `Umbraco.Templates::10.5.1` so I would be running in your exact reported version
2. Build and run the project
3. Install using SQLite 
4. Test website runs
5. Install Vendr 3.0.12 + Vendr SQLite provider (there is no 3.1.12 as reported)
6. Add `.AddVendr(b => b.AddSqlite())` to startup before `.AddComposers()`
7. Compile and run the solution
8. Create a store, create a homepage node with store picker, create a home node in content
9. Install Vendr Checkout `3.0.1-beta0001` from unstable feed (make sure to install this EXACT version as there are other newer ones in that feed)
10. Compile and run the solution
11. Go to settings section and open the Vendr Checkout dashboard (no errors)
12. Press the install button which opens install dialog
13. Select the new home node to install to
14. Click select and let install process run
15. Success message displays
16. Go to content section and check the checkout nodes were created

Unfortunately all of this ran without a hitch so I can't say that I can replicate this.

If your install steps were different can you please provide any additional steps you followed and the order in which you followed them, and anything else unique about your solution.

**Comment by craigs100** [comment]
Hi Matt,

It's an Umbraco Cloud site which was well down the site development route by the time it was decided to add Vendr.  Essentially it's what you have there but there would be other packages in place beforehand. Also I already had a home node called "home" to which I added the Store Entity Picker.

One more thing that "might" be an issue is that I develop on Linux so I'm always the canary in the cage for casing typos. I've caught a few on UmbForms and a couple of other packages.

I have a store running successfully up to the Cart which works great. So it's then that I tried to add the checkout package.

The packages installed are:-

    <PackageReference Include="Diplo.GodMode" Version="10.3.0" />
    <PackageReference Include="HotChilli.Umbraco.PageNotFound" Version="2.1.0" />
    <PackageReference Include="Our.Umbraco.Community.Contentment" Version="4.4.4" />
    <PackageReference Include="Our.Umbraco.FullTextSearch" Version="3.1.0" />
    <PackageReference Include="Our.Umbraco.TheDashboard" Version="10.0.1" />
    <PackageReference Include="Skybrud.Umbraco.Redirects" Version="4.0.8" />
    <PackageReference Include="Umbraco.Cloud.Cms.PublicAccess" Version="10.0.0" />
    <PackageReference Include="Umbraco.Cloud.Identity.Cms" Version="10.0.38" />
    <PackageReference Include="Umbraco.Cloud.StorageProviders.AzureBlob" Version="10.0.0" />
    <PackageReference Include="Umbraco.Cms" Version="10.5.1" />
    <PackageReference Include="Umbraco.Deploy.Cloud" Version="10.1.4" />
    <PackageReference Include="Umbraco.Deploy.Contrib" Version="10.1.1" />
    <PackageReference Include="Umbraco.Deploy.Forms" Version="10.2.2" />
    <PackageReference Include="Umbraco.Forms" Version="10.3.3" />
    <PackageReference Include="Umbraco.Forms.Integrations.Crm.Hubspot" Version="3.1.0" />
    <PackageReference Include="Vendr" Version="3.0.12" />
    <PackageReference Include="Vendr.Deploy" Version="3.0.0" />
    <PackageReference Include="Vendr.PaymentProviders.Stripe" Version="2.1.1" />
    <PackageReference Include="Vendr.Persistence.Sqlite" Version="3.0.12" />

**Comment by craigs100** [comment]
Actually, to clear the Linux thing up, I'll do exactly what you did on a fresh install. Though it won't be Cloud. Will report back when done.

**Comment by mattbrailsford** [comment]
That would be super useful to try and rule everything else out 👍🏻

**Comment by craigs100** [comment]
Did exactly the same as you except:-
Installed the Clean Starter kit, just to get a home node built quickly.
Had to add 
                .AddVendr(vendrBuilder => {
                    vendrBuilder.AddSQLite();
                })

to startup.cs instead of .AddVendr(b => b.AddSqlite()) because AddSqlite was errorring.

The top three Angular errors were there when I got to the settings section, the the last one arrived as soon as I clicked on the "Vendr Checkout" menu item.  Same as before, the install page loaded but nothing happened when the Install button clicked.

Total packages installed:-
```
    <PackageReference Include="clean" Version="2.1.6" />
    <PackageReference Include="Umbraco.Cms" Version="10.5.1" />
    <PackageReference Include="Vendr" Version="3.0.12" />
    <PackageReference Include="Vendr.Checkout" Version="3.0.1-beta0001" />
    <PackageReference Include="Vendr.Persistence.Sqlite" Version="3.0.12" />
```

**Comment by mattbrailsford** [comment]
Ok, then I’ll have to try and setup a Linux environment to see if I can replicate 🤦🏼‍♂️

**Comment by mattbrailsford** [comment]
Last check, are there any 404 errors in your network tab in dev tools?

**Comment by craigs100** [comment]
I repeated the exercise exactly as you had done this time, no extra packages and had the dev tools open throughout.  Console was clear before installing checkout package. As soon as that was installed, the first three error appeared and that was no matter what section of Umbraco was open. Just reloading the interface caused them to appear. Once again, as soon as the Vendr Checkout menu was clicked, the 4th error appeared. Again, the Install page loaded but button not working.
There were no 404 errors in the dev tools network tab at all.

If it's any use, you can install Linux Mint in a VM and use either VS Code or Rider as the IDE.  I use LM on the metal with Rider.  .net core installs easily and you won't need SQL Server (for this anyway ;) ).  However some like to get funky with that WSL thing in Windows ;)

Happy to help if needed.

**Comment by mattbrailsford** [comment]
Just a quite follow up, I honestly know nothing about setting up a Linux environment so I've got a member of the Umbraco Swat team taking a look at this to try and replicate it. I'll keep you posted on progress.

**Comment by craigs100** [comment]
No problem. Thanks for letting me know :)

**Comment by mattbrailsford** [comment]
For completeness I have spoken with @craigs100 externally and managed to debug this issue down to Umbraco not loading packages scripts in an expected order on Linux. I've raised this as an issue here https://github.com/umbraco/Umbraco-CMS/issues/14462 (which also documents a workaround) and have also submitted a PR to fix this here https://github.com/umbraco/Umbraco-CMS/pull/14466

As this is an issue in Umbraco CMS, I'm closing this issue.

**Comment by craigs100** [comment]
..... and fixed the path casing typo which also prevented installation? ;)  #lestweforget

**Comment by mattbrailsford** [comment]
Yup, but that was a different bug that would have warranted it's own issue 😁

**Comment by craigs100** [comment]
It was actually just another onion skin as it prevented items from installing. I named it well ;). The next onion skin is that the template items did not install. Possibly the install path to Views ??
